from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BankRegistration(object):
    def setupUi(self, BankRegistration):
        BankRegistration.setObjectName("BankRegistration")
        BankRegistration.resize(300, 800)
        BankRegistration.setMinimumSize(QtCore.QSize(300, 300))
        BankRegistration.setMaximumSize(QtCore.QSize(300, 800))
        self.centralwidget = QtWidgets.QWidget(parent=BankRegistration)
        self.centralwidget.setObjectName("centralwidget")
        self.label_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_header.setGeometry(QtCore.QRect(60, 10, 161, 16))
        self.label_header.setObjectName("label_header")
        self.radioButton_login = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_login.setGeometry(QtCore.QRect(180, 30, 71, 20))
        self.radioButton_login.setObjectName("radioButton_login")
        self.radioButton_create_acct = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_create_acct.setGeometry(QtCore.QRect(30, 30, 121, 20))
        self.radioButton_create_acct.setObjectName("radioButton_create_acct")
        self.button_enter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_enter.setGeometry(QtCore.QRect(80, 50, 113, 32))
        self.button_enter.setObjectName("button_enter")
        self.frame1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(10, 80, 280, 251))
        self.frame1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame1.setObjectName("frame1")
        self.label_name = QtWidgets.QLabel(parent=self.frame1)
        self.label_name.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.label_name.setObjectName("label_name")
        self.input_name = QtWidgets.QLineEdit(parent=self.frame1)
        self.input_name.setGeometry(QtCore.QRect(150, 20, 121, 15))
        self.input_name.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.input_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.input_name.setObjectName("input_name")
        self.label_age_acct_num = QtWidgets.QLabel(parent=self.frame1)
        self.label_age_acct_num.setGeometry(QtCore.QRect(10, 40, 151, 16))
        self.label_age_acct_num.setObjectName("label_age_acct_num")
        self.input_age_acct_num = QtWidgets.QLineEdit(parent=self.frame1)
        self.input_age_acct_num.setGeometry(QtCore.QRect(150, 40, 121, 15))
        self.input_age_acct_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.input_age_acct_num.setObjectName("input_age_acct_num")
        self.label_address = QtWidgets.QLabel(parent=self.frame1)
        self.label_address.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label_address.setObjectName("label_address")
        self.label_pin = QtWidgets.QLabel(parent=self.frame1)
        self.label_pin.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_pin.setObjectName("label_pin")
        self.label_set_balance = QtWidgets.QLabel(parent=self.frame1)
        self.label_set_balance.setGeometry(QtCore.QRect(10, 100, 81, 16))
        self.label_set_balance.setObjectName("label_set_balance")
        self.input_address = QtWidgets.QLineEdit(parent=self.frame1)
        self.input_address.setGeometry(QtCore.QRect(150, 60, 121, 15))
        self.input_address.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.input_address.setObjectName("input_address")
        self.input_pin = QtWidgets.QLineEdit(parent=self.frame1)
        self.input_pin.setGeometry(QtCore.QRect(150, 80, 121, 15))
        self.input_pin.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.input_pin.setObjectName("input_pin")
        self.input_set_balance = QtWidgets.QLineEdit(parent=self.frame1)
        self.input_set_balance.setGeometry(QtCore.QRect(150, 100, 121, 15))
        self.input_set_balance.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.input_set_balance.setObjectName("input_set_balance")
        self.label_welcome = QtWidgets.QLabel(parent=self.frame1)
        self.label_welcome.setGeometry(QtCore.QRect(10, 120, 261, 71))
        self.label_welcome.setText("")
        self.label_welcome.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_welcome.setWordWrap(True)
        self.label_welcome.setObjectName("label_welcome")
        self.button_login_create = QtWidgets.QPushButton(parent=self.frame1)
        self.button_login_create.setGeometry(QtCore.QRect(60, 200, 161, 32))
        self.button_login_create.setObjectName("button_login_create")
        self.frame2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame2.setGeometry(QtCore.QRect(10, 340, 281, 101))
        self.frame2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame2.setObjectName("frame2")
        self.label_select_transaction = QtWidgets.QLabel(parent=self.frame2)
        self.label_select_transaction.setGeometry(QtCore.QRect(50, 0, 161, 31))
        self.label_select_transaction.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_select_transaction.setObjectName("label_select_transaction")
        self.radioButton_deposit = QtWidgets.QRadioButton(parent=self.frame2)
        self.radioButton_deposit.setGeometry(QtCore.QRect(0, 30, 71, 20))
        self.radioButton_deposit.setObjectName("radioButton_deposit")
        self.radioButton_withdraw = QtWidgets.QRadioButton(parent=self.frame2)
        self.radioButton_withdraw.setGeometry(QtCore.QRect(80, 30, 81, 20))
        self.radioButton_withdraw.setObjectName("radioButton_withdraw")
        self.button_submit = QtWidgets.QPushButton(parent=self.frame2)
        self.button_submit.setGeometry(QtCore.QRect(80, 60, 113, 32))
        self.button_submit.setObjectName("button_submit")
        self.radioButton_balance = QtWidgets.QRadioButton(parent=self.frame2)
        self.radioButton_balance.setGeometry(QtCore.QRect(170, 30, 100, 20))
        self.radioButton_balance.setObjectName("radioButton_balance")
        self.frame3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame3.setGeometry(QtCore.QRect(10, 450, 281, 241))
        self.frame3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame3.setObjectName("frame3")
        self.label_transaction_type = QtWidgets.QLabel(parent=self.frame3)
        self.label_transaction_type.setGeometry(QtCore.QRect(10, 10, 111, 51))
        self.label_transaction_type.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_transaction_type.setObjectName("label_transaction_type")
        self.input_trans_amount = QtWidgets.QLineEdit(parent=self.frame3)
        self.input_trans_amount.setGeometry(QtCore.QRect(140, 10, 113, 21))
        self.input_trans_amount.setObjectName("input_trans_amount")
        self.button_complete = QtWidgets.QPushButton(parent=self.frame3)
        self.button_complete.setGeometry(QtCore.QRect(50, 70, 161, 32))
        self.button_complete.setObjectName("button_complete")
        self.label_avail_bal = QtWidgets.QLabel(parent=self.frame3)
        self.label_avail_bal.setGeometry(QtCore.QRect(10, 110, 231, 51))
        self.label_avail_bal.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_avail_bal.setWordWrap(True)
        self.label_avail_bal.setObjectName("label_avail_bal")
        self.button_logout = QtWidgets.QPushButton(parent=self.frame3)
        self.button_logout.setGeometry(QtCore.QRect(80, 190, 113, 32))
        self.button_logout.setObjectName("button_logout")
        BankRegistration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=BankRegistration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 37))
        self.menubar.setObjectName("menubar")
        BankRegistration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=BankRegistration)
        self.statusbar.setObjectName("statusbar")
        BankRegistration.setStatusBar(self.statusbar)

        self.retranslateUi(BankRegistration)
        QtCore.QMetaObject.connectSlotsByName(BankRegistration)

    def retranslateUi(self, BankRegistration):
        _translate = QtCore.QCoreApplication.translate
        BankRegistration.setWindowTitle(_translate("BankRegistration", "MainWindow"))
        self.label_header.setText(_translate("BankRegistration", "Welcome to V.S. Banking"))
        self.radioButton_login.setText(_translate("BankRegistration", "Login"))
        self.radioButton_create_acct.setText(_translate("BankRegistration", "Create Account"))
        self.button_enter.setText(_translate("BankRegistration", "Enter"))
        self.label_name.setText(_translate("BankRegistration", "Name:"))
        self.label_age_acct_num.setText(_translate("BankRegistration", "Age:"))
        self.label_address.setText(_translate("BankRegistration", "Address:"))
        self.label_pin.setText(_translate("BankRegistration", "Pin:"))
        self.label_set_balance.setText(_translate("BankRegistration", "Set Balance:"))
        self.button_login_create.setText(_translate("BankRegistration", "Login"))
        self.label_select_transaction.setText(_translate("BankRegistration", "Select Transaction Type"))
        self.radioButton_deposit.setText(_translate("BankRegistration", "Deposit"))
        self.radioButton_withdraw.setText(_translate("BankRegistration", "Withdraw"))
        self.button_submit.setText(_translate("BankRegistration", "Submit"))
        self.radioButton_balance.setText(_translate("BankRegistration", "Balance"))
        self.label_transaction_type.setText(_translate("BankRegistration", "transaction type"))
        self.button_complete.setText(_translate("BankRegistration", "Complete Transaction"))
        self.label_avail_bal.setText(_translate("BankRegistration", "Available Balance:"))
        self.button_logout.setText(_translate("BankRegistration", "Logout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BankRegistration = QtWidgets.QMainWindow()
    ui = Ui_BankRegistration()
    ui.setupUi(BankRegistration)
    BankRegistration.show()
    sys.exit(app.exec())
